#!/bin/bash
#
# Akeeba Build Files
#
# @package    buildfiles
# @copyright  (c) 2010-2019 Akeeba Ltd
#

usage () {
	echo -e $COLOR_BROWN"Usage: %0 <command>"$COLOR_NC
	echo ""
	echo -e $COLOR_BLUE"All repositories"$COLOR_NC
	echo "pull	  Pull from Git"
	echo "push	  Push to Git"
	echo "status  Report repositories with uncommitted changes"
	echo "branch  Which branch am I in?"
	echo -e $COLOR_BLUE"Using Akeeba Build Files"$COLOR_NC
	echo "link    Internal relink"
	echo -e $COLOR_BLUE"Using Transifex"$COLOR_NC
	echo "txpush  Push source translations to Trasnifex"
	echo "txpull  Pull all translations from Transifex"

	exit 255
}

COLOR_NC='\033[0m'
COLOR_WHITE='\033[1;37m'
COLOR_BLACK='\033[0;30m'
COLOR_BLUE='\033[0;34m'
COLOR_LIGHT_BLUE='\033[1;34m'
COLOR_GREEN='\033[0;32m'
COLOR_LIGHT_GREEN='\033[1;32m'
COLOR_CYAN='\033[0;36m'
COLOR_LIGHT_CYAN='\033[1;36m'
COLOR_RED='\033[0;31m'
COLOR_LIGHT_RED='\033[1;31m'
COLOR_PURPLE='\033[0;35m'
COLOR_LIGHT_PURPLE='\033[1;35m'
COLOR_BROWN='\033[0;33m'
COLOR_YELLOW='\033[1;33m'
COLOR_GRAY='\033[0;30m'
COLOR_LIGHT_GRAY='\033[0;37m'

if [ $# -lt 1 ]
then
	usage

	exit 255
fi

echo -e $COLOR_WHITE"All – Loop all Git repositories"$COLOR_NC
echo ""

for d in */
do
	pushd $d > /dev/null

	if [ ! -d ".git" ]
	then
		popd > /dev/null

		continue
	fi

	THISREPO_LINES=`git remote -v | grep git@github.com | wc -l | awk '{print $1}'`

	if [ $THISREPO_LINES -lt 1 ]
	then
		popd > /dev/null

		continue
	fi

	case "$1" in
		pull )
			echo -e "\n"$COLOR_LIGHT_BLUE"Pulling $COLOR_CYAN$d"$COLOR_NC
			git pull --all
			;;

		push )
			echo -e "\n"$COLOR_LIGHT_GREEN"Pushing $COLOR_CYAN$d"$COLOR_NC
			git push
			git push --tags
			;;

        branch )
            ZZZ_CUR_BRANCH=`git rev-parse --abbrev-ref HEAD`
            ZZZ_COLOR=$COLOR_LIGHT_RED

			if [[ "$ZZZ_CUR_BRANCH" == "development" ]]
			then
                ZZZ_COLOR=$COLOR_LIGHT_GREEN
            elif [[ "$ZZZ_CUR_BRANCH" == "master" ]]
            then
                ZZZ_COLOR=$COLOR_YELLOW
            fi
            
            echo -ne $COLOR_LIGHT_PURPLE"Branch "$COLOR_CYAN
            printf '%-25s' $d
			echo -e $ZZZ_COLOR$ZZZ_CUR_BRANCH$COLOR_NC
			;;

        status )
			#i=`expr $(git status --porcelain 2>/dev/null| egrep "^(M| M)" | wc -l)`
			i=`expr $(git status --porcelain 2>/dev/null| wc -l)`
			if [ $i -ne 0 ]
			then
				echo -e $COLOR_LIGHT_RED"Dirty $COLOR_CYAN$d"$COLOR_NC
			fi
			;;
			
		link )
			if [ -d build ]
			then
				echo -e "\n"$COLOR_BROWN"Linking $COLOR_CYAN$d"$COLOR_NC
				cd build
				phing link
			fi
			;;

		txpush )
			if [ -f ./.tx/config ]
			then
				echo -e "\n"$COLOR_PURPLE"Pushing translations for $COLOR_CYAN$d"$COLOR_NC
				tx push -s
			fi
			;;

		txpull )
			if [ -f ./.tx/config ]
			then
				echo -e "\n"$COLOR_PURPLE"Pulling translations for $COLOR_CYAN$d"$COLOR_NC
				tx pull -a
			fi
			;;

		* )
			echo Unknown command "$1"
			;;
	esac

	popd > /dev/null
done
